"""Extract MNIST-8 ONNX weights and emit a TypeScript module with inlined Float32Arrays."""
import onnx
import struct
import os

model = onnx.load('public/models/mnist-8.onnx')
graph = model.graph

# Build name -> float list map
weights = {}
for init in graph.initializer:
    raw = init.raw_data
    if raw:
        n = len(raw) // 4
        floats = list(struct.unpack(str(n) + 'f', raw))
    else:
        floats = list(init.float_data)
    if floats:
        weights[init.name] = floats

def fmt(floats):
    # Compact float format, 6 significant digits
    parts = []
    for f in floats:
        s = '{:.6g}'.format(f)
        parts.append(s)
    return ','.join(parts)

out_path = 'src/utils/mnistWeights.ts'
with open(out_path, 'w') as f:
    f.write('// Auto-generated by scripts/extract-weights.py — do not edit\n')
    f.write('// MNIST-8 model weights (5994 floats, ~24KB raw)\n\n')
    for name, floats in weights.items():
        safe = name.replace('/', '_').replace('.', '_')
        f.write('export const ' + safe + ' = new Float32Array([' + fmt(floats) + '])\n')

size = os.path.getsize(out_path)
print('Generated', out_path, ':', size, 'bytes')
for name, floats in weights.items():
    print(' ', name, ':', len(floats), 'floats')
